# Generated by Django 2.2.2 on 2019-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190612_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
